### ISSUE TITLE
Image URLs not being re-written properly via Tor

### ISSUE THREAD

**Issue by TheFiZi** [straube/multiple-domain#32] opened 2018-11-11 01:40 UTC
Another Tor related issue.

If you go to https://www.pickysysadmin.ca/2018/11/10/how-to-almost-automatically-backup-your-steam-library/

The first image has the following links associated with it:
* Image location: https://www.pickysysadmin.ca/wp-content/uploads/2018/10/SteamGamesDriveEnableCompression.png
* When clicked link: https://www.pickysysadmin.ca/wp-content/uploads/2018/10/SteamGamesDriveEnableCompression.png

If you browse to it via Tor (http://27i7rsfkhoanzabw.onion/2018/11/10/how-to-almost-automatically-backup-your-steam-library/) the following is displayed for the same image:
* Image location: http://27i7rsfkhoanzabw.onion/wp-content/uploads/2018/10/SteamGamesDriveEnableCompression.png
* When clicked link: http://27i7rsfkhoanzabw.onion/2018/11/10/how-to-almost-automatically-backup-your-steam-library/7i7rsfkhoanzabw.onion/wp-content/uploads/2018/10/SteamGamesDriveEnableCompression.png

The clicked link is being re-written twice?

**Note:** I manually edited the Tor links per [issue 31](https://github.com/straube/multiple-domain/issues/31)

**Comment by straube** [comment] 2018-11-13 15:20
@TheFiZi This is definitely a bug. I have almost no free time to work on this around these days. But as soon as I have a chance, I'll write a fix for this. In the meantime, if you find a solution, feel free to submit a PR. :)

**Comment by straube** [comment] 2018-12-14 22:34
@TheFiZi Have you figured out a way to fix this issue? If you haven't, could you help me debug this issue? I need to check how the content looks like before the plugin replaces the URLs. Adding the `var_dump` call below to line 313 would print out that value:

    var_dump($content);

This is just after the following lines:

    public function fixContentUrls($content)
    {
        if (array_key_exists($this->domain, $this->domains)) {
            // Add the var_dump here

**Comment by TheFiZi** [comment] 2018-12-19 04:07
Sorry for the delay.

I've inserted the code and you can view the results by going to http://27i7rsfkhoanzabw.onion/ via the Tor Browser.

Here is a screenshot of an example. I'm not sure if it's outputting the data you want.

![image](https://user-images.githubusercontent.com/1762426/50198453-9a974900-0300-11e9-8a28-f28ccf669b47.png)

**Closed as completed** 2018-12-19 14:56 UTC
Labels: bug, help wanted

**Comment by straube** [comment] 2018-12-19 15:05
@TheFiZi Thanks to your help, I was able to track the bug down.

The issue is now fixed and a new version was released: **0.8.2**. Please update it in your Wordpress instance and let me know how it goes.

**Comment by TheFiZi** [comment] 2018-12-20 02:53
@straube I think that's got it fixed. The links all look correct now.

Things still aren't loading properly but that's because of issue #31 :)
